import Navigation from "../components/navigation";
import Head from "next/head";
import favicon from '../../public/favicon.ico'

interface MainLayout{
  children:JSX.Element

}

function MainLayout({children}:MainLayout){
  return(
	  <>
		<Head>
		  <title>Vetrehab - Rehabilitacja weterynaryjna</title>
		  <meta name="description" content="Generated by create next app"/>
		  <link rel="icon" href='/favicon.ico'/>
		</Head>
		<Navigation/>
		{children}
	  </>
  )
}

export default MainLayout;
